### ISSUE TITLE
TypeError: Cannot read property 'afterEmit' of undefined

### ISSUE THREAD

**Issue by shreyas-a** [GoogleChromeLabs/size-plugin#10] opened 2018-08-27 07:00 UTC

**Comment by shreyas-a** [comment] 2018-08-27 07:01
I tried to integrated it with [vue hacker-news boilerplate](https://github.com/vuejs/vue-hackernews-2.0) project, but it throws this type error.

**Comment by kemalcany** [comment] 2018-08-27 14:28
I have the same issue: Here's more content to the error I am receiving 

(Trying to add this to the Nuxt config (v.1.4.2)

```
 ERROR 

  TypeError: Cannot read property 'afterEmit' of undefined
  
  - size-plugin.js:76 SizePlugin.<anonymous>
    [www]/[size-plugin]/dist/size-plugin.js:76:24
  
  - new Promise
  
  - size-plugin.js:70 SizePlugin.apply
    [www]/[size-plugin]/dist/size-plugin.js:70:12
  
  - Tapable.js:375 Compiler.apply
    [www]/[tapable]/lib/Tapable.js:375:16
  
  - webpack.js:33 webpack
    [www]/[webpack]/lib/webpack.js:33:19
  
  - builder.js:524 compilers.compilersOptions.map.compilersOption
    [www]/[nuxt]/lib/builder/builder.js:524:24
  
  - Array.map
  
  - builder.js:523 Builder.webpackBuild
    [www]/[nuxt]/lib/builder/builder.js:523:39
  
  - builder.js:168 Builder.build
    [www]/[nuxt]/lib/builder/builder.js:168:16
```

**Comment by developit** [comment] 2018-08-27 14:56
This plugin currently requires Webpack 4+, looks like you're using a prior version.
Closing since this is a duplicate of #3.

**Closed by developit** 2018-08-27 14:56 UTC
